import java.math.BigInteger; 
import java.security.MessageDigest; 
import java.security.NoSuchAlgorithmException; 
  
class Sha{ 
    public static String getSHA(String input) 
    {   
        try { 

            MessageDigest md = MessageDigest.getInstance("SHA-1"); 

            byte[] messageDigest = md.digest(input.getBytes()); 
  
            BigInteger no = new BigInteger(1, messageDigest); 
   
            String hashtext = no.toString(16); 
  
             return hashtext; 
        } 
  
 
        catch (NoSuchAlgorithmException e) { 
            System.out.println("Exception thrown"
                               + " for incorrect algorithm: " + e); 
            return null; 
        } 
    } 
  

    public static void main(String args[]) throws NoSuchAlgorithmException 
    { 
        System.out.println("HashCode Generated by SHA-1 for:"); 
  
        String s1 = "Dolly"; 
        System.out.println("\n" + s1 + " : " + getSHA(s1)); 
    } 
}